<?php
return array (
  'app' => 'Admin',
  'model' => 'App',
  'action' => 'default',
  'data' => '',
  'type' => '1',
  'status' => '1',
  'name' => 'APP&amp;API',
  'icon' => 'magnet',
  'remark' => '',
  'listorder' => '80',
  'children' => 
  array (
    array (
      'app' => 'Admin',
      'model' => 'App',
      'action' => 'main',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => 'APP管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '1',
      'children' => 
      array (
        array (
          'app' => 'Admin',
          'model' => 'App',
          'action' => 'add',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '添加APP',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Admin',
              'model' => 'App',
              'action' => 'add_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '添加保存',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Admin',
          'model' => 'App',
          'action' => 'edit',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '修改',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Admin',
              'model' => 'App',
              'action' => 'edit_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '修改保存',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Admin',
          'model' => 'App',
          'action' => 'del',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '删除',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Admin',
          'model' => 'App',
          'action' => 'index',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => 'APP列表',
          'icon' => '',
          'remark' => '',
          'listorder' => '4',
        ),
        array (
          'app' => 'Admin',
          'model' => 'App',
          'action' => 'upgrade',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => 'APP版本管理',
          'icon' => '',
          'remark' => '',
          'listorder' => '6',
          'children' => 
          array (
            array (
              'app' => 'Admin',
              'model' => 'App',
              'action' => 'upgrade_add',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '添加',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
              'children' => 
              array (
                array (
                  'app' => 'Admin',
                  'model' => 'App',
                  'action' => 'upgrade_add_post',
                  'data' => '',
                  'type' => '1',
                  'status' => '0',
                  'name' => '添加保存',
                  'icon' => '',
                  'remark' => '',
                  'listorder' => '0',
                ),
              ),
            ),
            array (
              'app' => 'Admin',
              'model' => 'App',
              'action' => 'upgrade_edit',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '编辑',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
              'children' => 
              array (
                array (
                  'app' => 'Admin',
                  'model' => 'App',
                  'action' => 'upgrade_edit_post',
                  'data' => '',
                  'type' => '1',
                  'status' => '0',
                  'name' => '编辑保存',
                  'icon' => '',
                  'remark' => '',
                  'listorder' => '0',
                ),
              ),
            ),
            array (
              'app' => 'Admin',
              'model' => 'App',
              'action' => 'upgrade_del',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '删除',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Admin',
          'model' => 'Device',
          'action' => 'index',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '安装设备',
          'icon' => '',
          'remark' => '',
          'listorder' => '9',
          'children' => 
          array (
            array (
              'app' => 'Admin',
              'model' => 'Device',
              'action' => 'info',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '详情',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
      ),
    ),
    array (
      'app' => 'Admin',
      'model' => 'Api',
      'action' => 'default',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => 'API管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '4',
      'children' => 
      array (
        array (
          'app' => 'Admin',
          'model' => 'Api',
          'action' => 'add',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '添加API',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Admin',
              'model' => 'Api',
              'action' => 'add_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '添加保存',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Admin',
          'model' => 'Api',
          'action' => 'params',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => 'API参数',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Admin',
              'model' => 'Api',
              'action' => 'params_add',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '添加',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
              'children' => 
              array (
                array (
                  'app' => 'Admin',
                  'model' => 'Api',
                  'action' => 'params_add_post',
                  'data' => '',
                  'type' => '1',
                  'status' => '0',
                  'name' => '添加保存',
                  'icon' => '',
                  'remark' => '',
                  'listorder' => '0',
                ),
              ),
            ),
            array (
              'app' => 'Admin',
              'model' => 'Api',
              'action' => 'params_edit',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '编辑',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
              'children' => 
              array (
                array (
                  'app' => 'Admin',
                  'model' => 'Api',
                  'action' => 'params_edit_post',
                  'data' => '',
                  'type' => '1',
                  'status' => '0',
                  'name' => '编辑保存',
                  'icon' => '',
                  'remark' => '',
                  'listorder' => '0',
                ),
              ),
            ),
            array (
              'app' => 'Admin',
              'model' => 'Api',
              'action' => 'params_del',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '删除',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Admin',
              'model' => 'Api',
              'action' => 'params_listorder',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '排序',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Admin',
          'model' => 'Api',
          'action' => 'response',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '响应数据',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Admin',
              'model' => 'Api',
              'action' => 'response_add',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '添加',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
              'children' => 
              array (
                array (
                  'app' => 'Admin',
                  'model' => 'Api',
                  'action' => 'response_add_post',
                  'data' => '',
                  'type' => '1',
                  'status' => '0',
                  'name' => '添加保存',
                  'icon' => '',
                  'remark' => '',
                  'listorder' => '0',
                ),
              ),
            ),
            array (
              'app' => 'Admin',
              'model' => 'Api',
              'action' => 'response_edit',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '编辑',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
              'children' => 
              array (
                array (
                  'app' => 'Admin',
                  'model' => 'Api',
                  'action' => 'response_edit_post',
                  'data' => '',
                  'type' => '1',
                  'status' => '0',
                  'name' => '编辑保存',
                  'icon' => '',
                  'remark' => '',
                  'listorder' => '0',
                ),
              ),
            ),
            array (
              'app' => 'Admin',
              'model' => 'Api',
              'action' => 'response_del',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '删除',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Admin',
              'model' => 'Api',
              'action' => 'response_listorder',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '排序',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Admin',
          'model' => 'Apigroup',
          'action' => 'index',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '分组管理',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Admin',
              'model' => 'Apigroup',
              'action' => 'listorder',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '排序',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Admin',
              'model' => 'Apigroup',
              'action' => 'add',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '添加',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
              'children' => 
              array (
                array (
                  'app' => 'Admin',
                  'model' => 'Apigroup',
                  'action' => 'add_post',
                  'data' => '',
                  'type' => '1',
                  'status' => '0',
                  'name' => '添加保存',
                  'icon' => '',
                  'remark' => '',
                  'listorder' => '0',
                ),
              ),
            ),
            array (
              'app' => 'Admin',
              'model' => 'Apigroup',
              'action' => 'edit',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '编辑',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
              'children' => 
              array (
                array (
                  'app' => 'Admin',
                  'model' => 'Apigroup',
                  'action' => 'edit_post',
                  'data' => '',
                  'type' => '1',
                  'status' => '0',
                  'name' => '编辑保存',
                  'icon' => '',
                  'remark' => '',
                  'listorder' => '0',
                ),
              ),
            ),
            array (
              'app' => 'Admin',
              'model' => 'Apigroup',
              'action' => 'del',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '删除',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Admin',
          'model' => 'Api',
          'action' => 'index',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => 'API列表',
          'icon' => '',
          'remark' => '',
          'listorder' => '2',
          'children' => 
          array (
            array (
              'app' => 'Admin',
              'model' => 'Api',
              'action' => 'edit',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '编辑API',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
              'children' => 
              array (
                array (
                  'app' => 'Admin',
                  'model' => 'Api',
                  'action' => 'edit_post',
                  'data' => '',
                  'type' => '1',
                  'status' => '0',
                  'name' => '编辑保存',
                  'icon' => '',
                  'remark' => '',
                  'listorder' => '0',
                ),
              ),
            ),
            array (
              'app' => 'Admin',
              'model' => 'Api',
              'action' => 'del',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '删除API',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Admin',
          'model' => 'Api',
          'action' => 'doc',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '接口文档',
          'icon' => '',
          'remark' => '',
          'listorder' => '3',
        ),
      ),
    ),
    array (
      'app' => 'Admin',
      'model' => 'Log',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '日志',
      'icon' => '',
      'remark' => '',
      'listorder' => '8',
      'children' => 
      array (
        array (
          'app' => 'Admin',
          'model' => 'Log',
          'action' => 'api',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => 'API日志',
          'icon' => '',
          'remark' => '',
          'listorder' => '1',
          'children' => 
          array (
            array (
              'app' => 'Admin',
              'model' => 'Log',
              'action' => 'api_info',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '详情',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Admin',
          'model' => 'Log',
          'action' => 'app_error',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => 'APP日志',
          'icon' => '',
          'remark' => '',
          'listorder' => '2',
          'children' => 
          array (
            array (
              'app' => 'Admin',
              'model' => 'Log',
              'action' => 'app_error_info',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '详情',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
      ),
    ),
  ),
);