<?php
return array (
  'app' => 'Wechat',
  'model' => 'Wechat',
  'action' => 'default',
  'data' => '',
  'type' => '0',
  'status' => '1',
  'name' => '微信',
  'icon' => 'wechat',
  'remark' => '',
  'listorder' => '60',
  'children' => 
  array (
    array (
      'app' => 'Wechat',
      'model' => 'AdminMp',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '公众号管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
      'children' => 
      array (
        array (
          'app' => 'Wechat',
          'model' => 'AdminMp',
          'action' => 'add',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '添加公众号',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Wechat',
              'model' => 'AdminMp',
              'action' => 'add_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '添加公众号提交',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Wechat',
          'model' => 'AdminMp',
          'action' => 'edit',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '修改公众号',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Wechat',
              'model' => 'AdminMp',
              'action' => 'edit_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '修改公众号提交',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Wechat',
          'model' => 'AdminMp',
          'action' => 'delete',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '删除公众号',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
      ),
    ),
    array (
      'app' => 'Wechat',
      'model' => 'Wechat',
      'action' => 'menu',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '菜单',
      'icon' => '',
      'remark' => '',
      'listorder' => '1',
      'children' => 
      array (
        array (
          'app' => 'Wechat',
          'model' => 'AdminMenu',
          'action' => 'index',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '自定义菜单',
          'icon' => 'bars',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Wechat',
              'model' => 'AdminMenu',
              'action' => 'add',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '添加自定义菜单',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
              'children' => 
              array (
                array (
                  'app' => 'Wechat',
                  'model' => 'AdminMenu',
                  'action' => 'add_post',
                  'data' => '',
                  'type' => '1',
                  'status' => '0',
                  'name' => '添加自定义菜单提交',
                  'icon' => '',
                  'remark' => '',
                  'listorder' => '0',
                ),
              ),
            ),
            array (
              'app' => 'Wechat',
              'model' => 'AdminMenu',
              'action' => 'edit',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '修改自定义菜单',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
              'children' => 
              array (
                array (
                  'app' => 'Wechat',
                  'model' => 'AdminMenu',
                  'action' => 'edit_post',
                  'data' => '',
                  'type' => '1',
                  'status' => '0',
                  'name' => '修改自定义菜单提交',
                  'icon' => '',
                  'remark' => '',
                  'listorder' => '0',
                ),
              ),
            ),
            array (
              'app' => 'Wechat',
              'model' => 'AdminMenu',
              'action' => 'delete',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '自定义菜单删除',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Wechat',
              'model' => 'AdminMenu',
              'action' => 'listorders',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '自定义菜单排序',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Wechat',
              'model' => 'AdminMenu',
              'action' => 'makemenu',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '生成微信菜单',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Wechat',
              'model' => 'AdminMenu',
              'action' => 'delmenu',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '删除微信菜单',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Wechat',
          'model' => 'AdminSpecialmenu',
          'action' => 'class_index',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '个性化菜单',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Wechat',
              'model' => 'AdminSpecialmenu',
              'action' => 'class_add',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '个性化规则添加',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
              'children' => 
              array (
                array (
                  'app' => 'Wechat',
                  'model' => 'AdminSpecialmenu',
                  'action' => 'class_add_post',
                  'data' => '',
                  'type' => '1',
                  'status' => '0',
                  'name' => '提交个性化规则添加',
                  'icon' => '',
                  'remark' => '',
                  'listorder' => '0',
                ),
              ),
            ),
            array (
              'app' => 'Wechat',
              'model' => 'AdminSpecialmenu',
              'action' => 'class_edit',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '个性化规则编辑',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
              'children' => 
              array (
                array (
                  'app' => 'Wechat',
                  'model' => 'AdminSpecialmenu',
                  'action' => 'class_edit_post',
                  'data' => '',
                  'type' => '1',
                  'status' => '0',
                  'name' => '提交个性化规则编辑',
                  'icon' => '',
                  'remark' => '',
                  'listorder' => '0',
                ),
              ),
            ),
            array (
              'app' => 'Wechat',
              'model' => 'AdminSpecialmenu',
              'action' => 'class_delete',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '个性化规则删除',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Wechat',
              'model' => 'AdminSpecialmenu',
              'action' => 'menu_index',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '个性化菜单列表',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Wechat',
              'model' => 'AdminSpecialmenu',
              'action' => 'menu_add',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '个性化菜单添加',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
              'children' => 
              array (
                array (
                  'app' => 'Wechat',
                  'model' => 'AdminSpecialmenu',
                  'action' => 'menu_add_post',
                  'data' => '',
                  'type' => '1',
                  'status' => '0',
                  'name' => '提交个性化菜单添加',
                  'icon' => '',
                  'remark' => '',
                  'listorder' => '0',
                ),
              ),
            ),
            array (
              'app' => 'Wechat',
              'model' => 'AdminSpecialmenu',
              'action' => 'menu_edit',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '个性化菜单编辑',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
              'children' => 
              array (
                array (
                  'app' => 'Wechat',
                  'model' => 'AdminSpecialmenu',
                  'action' => 'menu_edit_post',
                  'data' => '',
                  'type' => '1',
                  'status' => '0',
                  'name' => '提交个性化菜单编辑',
                  'icon' => '',
                  'remark' => '',
                  'listorder' => '0',
                ),
              ),
            ),
            array (
              'app' => 'Wechat',
              'model' => 'AdminSpecialmenu',
              'action' => 'menu_listorders',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '个性化菜单排序',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Wechat',
              'model' => 'AdminSpecialmenu',
              'action' => 'menu_delete',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '个性化菜单删除',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Wechat',
              'model' => 'AdminSpecialmenu',
              'action' => 'makemenu',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '微信个性化菜单生成',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Wechat',
              'model' => 'AdminSpecialmenu',
              'action' => 'delmenu',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '微信个性化菜单删除',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
      ),
    ),
    array (
      'app' => 'Wechat',
      'model' => 'AdminFans',
      'action' => 'default',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '用户管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '2',
      'children' => 
      array (
        array (
          'app' => 'Wechat',
          'model' => 'AdminFans',
          'action' => 'index',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '粉丝管理',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Wechat',
              'model' => 'AdminFans',
              'action' => 'delete',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '删除粉丝',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Wechat',
              'model' => 'AdminFans',
              'action' => 'sync',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '同步粉丝信息',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Wechat',
              'model' => 'AdminFans',
              'action' => 'refresh',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '刷新粉丝接口信息',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Wechat',
              'model' => 'AdminFans',
              'action' => 'forever_qr',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '生成永久推广码',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Wechat',
          'model' => 'AdminFans',
          'action' => 'edit',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '粉丝信息编辑',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Wechat',
              'model' => 'AdminFans',
              'action' => 'edit_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '粉丝信息编辑提交',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Wechat',
          'model' => 'AdminFanslabel',
          'action' => 'index',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '用户标签',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Wechat',
              'model' => 'AdminFanslabel',
              'action' => 'add',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '添加标签',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
              'children' => 
              array (
                array (
                  'app' => 'Wechat',
                  'model' => 'AdminFanslabel',
                  'action' => 'add_post',
                  'data' => '',
                  'type' => '1',
                  'status' => '0',
                  'name' => '添加标签提交',
                  'icon' => '',
                  'remark' => '',
                  'listorder' => '0',
                ),
              ),
            ),
            array (
              'app' => 'Wechat',
              'model' => 'AdminFanslabel',
              'action' => 'edit',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '修改标签',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
              'children' => 
              array (
                array (
                  'app' => 'Wechat',
                  'model' => 'AdminFanslabel',
                  'action' => 'edit_post',
                  'data' => '',
                  'type' => '1',
                  'status' => '0',
                  'name' => '修改标签提交',
                  'icon' => '',
                  'remark' => '',
                  'listorder' => '0',
                ),
              ),
            ),
            array (
              'app' => 'Wechat',
              'model' => 'AdminFanslabel',
              'action' => 'delete',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '删除标签',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Wechat',
              'model' => 'AdminFanslabel',
              'action' => 'sync',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '同步标签',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Wechat',
              'model' => 'AdminFanslabel',
              'action' => 'syncuserlabel',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '同步标签用户',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
      ),
    ),
    array (
      'app' => 'Wechat',
      'model' => 'AdminMessage',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '自动回复',
      'icon' => '',
      'remark' => '',
      'listorder' => '3',
      'children' => 
      array (
        array (
          'app' => 'Wechat',
          'model' => 'AdminMessage',
          'action' => 'add',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '自动回复添加',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Wechat',
              'model' => 'AdminMessage',
              'action' => 'add_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '自动回复添加提交',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Wechat',
          'model' => 'AdminMessage',
          'action' => 'edit',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '自动回复编辑',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Wechat',
              'model' => 'AdminMessage',
              'action' => 'edit_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '自动回复编辑提交',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Wechat',
          'model' => 'AdminMessage',
          'action' => 'delete',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '自动回复删除',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Portal',
          'model' => 'AdminPost',
          'action' => 'wechat',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '公众号图文信息添加',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Wechat',
          'model' => 'AdminMessage',
          'action' => 'subscribe',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '关注回复设置',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Wechat',
          'model' => 'AdminMessage',
          'action' => 'noanswer',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '回答不上了配置',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
      ),
    ),
    array (
      'app' => 'Wechat',
      'model' => 'AdminTplmsg',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '模板消息',
      'icon' => '',
      'remark' => '',
      'listorder' => '4',
      'children' => 
      array (
        array (
          'app' => 'Wechat',
          'model' => 'AdminTplmsg',
          'action' => 'sync',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '模板消息同步',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Wechat',
          'model' => 'AdminTplmsg',
          'action' => 'setcolor',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '设置颜色',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Wechat',
              'model' => 'AdminTplmsg',
              'action' => 'setcolor_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '提交设置颜色',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Wechat',
          'model' => 'AdminTplmsg',
          'action' => 'delete',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '模板消息删除',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
      ),
    ),
    array (
      'app' => 'Wechat',
      'model' => 'AdminQrcode',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '二维码列表',
      'icon' => '',
      'remark' => '',
      'listorder' => '6',
    ),
    array (
      'app' => 'Activity',
      'model' => 'AdminMorning',
      'action' => 'default',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '早起打卡',
      'icon' => '',
      'remark' => '',
      'listorder' => '21',
      'children' => 
      array (
        array (
          'app' => 'Activity',
          'model' => 'AdminMorning',
          'action' => 'index',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '打卡列表',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Activity',
          'model' => 'AdminMorning',
          'action' => 'stat',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '每日统计',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Activity',
          'model' => 'AdminMorning',
          'action' => 'config',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '配置',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
      ),
    ),
  ),
);